################################# Default configuration ###################
baseURL = "https://www.devopzilla.com"
title = "DevopZilla"
theme = "meghna-hugo"
# themesDir = "../.."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
# [[Languages.en.menu.main]]
# name = "events"
# url = "events"
# weight = 1

[[Languages.en.menu.main]]
name = "About"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "Services"
url = "#services"
weight = 2

# [[Languages.en.menu.main]]
# name = "portfolio"
# url = "#portfolio"
# weight = 3

# [[Languages.en.menu.main]]
# name = "team"
# url = "#team"
# weight = 4

# [[Languages.en.menu.main]]
# name = "pricing"
# url = "#pricing"
# weight = 5

[[Languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 6

[[Languages.en.menu.main]]
name = "Contact"
url = "#contact"
weight = 7


############################# Default Parameters ##########################
[params]
logo =  "devopzilla_logo_simpler.svg"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# social icons ##########################
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/devopzilla"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/dvpzla"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2021 DevopZilla, Theme Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
